<?php

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder {
    public function run() {
        Country::create(['name' => 'Afghanistan', 'alpha_2' => 'AF']);
        Country::create(['name' => 'Aland Islands', 'alpha_2' => 'AX']);
        Country::create(['name' => 'Albania', 'alpha_2' => 'AL']);
        Country::create(['name' => 'Algeria', 'alpha_2' => 'DZ']);
        Country::create(['name' => 'American Samoa', 'alpha_2' => 'AS']);
        Country::create(['name' => 'Andorra', 'alpha_2' => 'AD']);
        Country::create(['name' => 'Angola', 'alpha_2' => 'AO']);
        Country::create(['name' => 'Anguilla', 'alpha_2' => 'AI']);
        Country::create(['name' => 'Antarctica', 'alpha_2' => 'AQ']);
        Country::create(['name' => 'Antigua and Barbuda', 'alpha_2' => 'AG']);
        Country::create(['name' => 'Argentina', 'alpha_2' => 'AR']);
        Country::create(['name' => 'Armenia', 'alpha_2' => 'AM']);
        Country::create(['name' => 'Aruba', 'alpha_2' => 'AW']);
        Country::create(['name' => 'Australia', 'alpha_2' => 'AU']);
        Country::create(['name' => 'Austria', 'alpha_2' => 'AT']);
        Country::create(['name' => 'Azerbaijan', 'alpha_2' => 'AZ']);
        Country::create(['name' => 'Bahamas', 'alpha_2' => 'BS']);
        Country::create(['name' => 'Bahrain', 'alpha_2' => 'BH']);
        Country::create(['name' => 'Bangladesh', 'alpha_2' => 'BD']);
        Country::create(['name' => 'Barbados', 'alpha_2' => 'BB']);
        Country::create(['name' => 'Belarus', 'alpha_2' => 'BY']);
        Country::create(['name' => 'Belgium', 'alpha_2' => 'BE']);
        Country::create(['name' => 'Belize', 'alpha_2' => 'BZ']);
        Country::create(['name' => 'Benin', 'alpha_2' => 'BJ']);
        Country::create(['name' => 'Bermuda', 'alpha_2' => 'BM']);
        Country::create(['name' => 'Bhutan', 'alpha_2' => 'BT']);
        Country::create(['name' => 'Bolivia', 'alpha_2' => 'BO']);
        Country::create(['name' => 'Bosnia and Herzegovina', 'alpha_2' => 'BA']);
        Country::create(['name' => 'Botswana', 'alpha_2' => 'BW']);
        Country::create(['name' => 'Bouvet Island', 'alpha_2' => 'BV']);
        Country::create(['name' => 'Brazil', 'alpha_2' => 'BR']);
        Country::create(['name' => 'British Virgin Islands', 'alpha_2' => 'VG']);
        Country::create(['name' => 'British Indian Ocean Territory', 'alpha_2' => 'IO']);
        Country::create(['name' => 'Brunei Darussalam', 'alpha_2' => 'BN']);
        Country::create(['name' => 'Bulgaria', 'alpha_2' => 'BG']);
        Country::create(['name' => 'Burkina Faso', 'alpha_2' => 'BF']);
        Country::create(['name' => 'Burundi', 'alpha_2' => 'BI']);
        Country::create(['name' => 'Cambodia', 'alpha_2' => 'KH']);
        Country::create(['name' => 'Cameroon', 'alpha_2' => 'CM']);
        Country::create(['name' => 'Canada', 'alpha_2' => 'CA']);
        Country::create(['name' => 'Cape Verde', 'alpha_2' => 'CV']);
        Country::create(['name' => 'Cayman Islands', 'alpha_2' => 'KY']);
        Country::create(['name' => 'Central African Republic', 'alpha_2' => 'CF']);
        Country::create(['name' => 'Chad', 'alpha_2' => 'TD']);
        Country::create(['name' => 'Chile', 'alpha_2' => 'CL']);
        Country::create(['name' => 'China', 'alpha_2' => 'CN']);
        Country::create(['name' => 'Hong Kong', 'alpha_2' => 'HK']);
        Country::create(['name' => 'Macao', 'alpha_2' => 'MO']);
        Country::create(['name' => 'Christmas Island', 'alpha_2' => 'CX']);
        Country::create(['name' => 'Cocos (Keeling) Islands', 'alpha_2' => 'CC']);
        Country::create(['name' => 'Colombia', 'alpha_2' => 'CO']);
        Country::create(['name' => 'Comoros', 'alpha_2' => 'KM']);
        Country::create(['name' => 'Congo', 'alpha_2' => 'CG']);
        Country::create(['name' => 'Cook Islands', 'alpha_2' => 'CK']);
        Country::create(['name' => 'Costa Rica', 'alpha_2' => 'CR']);
        Country::create(['name' => 'Côte d\'Ivoire', 'alpha_2' => 'CI']);
        Country::create(['name' => 'Croatia', 'alpha_2' => 'HR']);
        Country::create(['name' => 'Cuba', 'alpha_2' => 'CU']);
        Country::create(['name' => 'Cyprus', 'alpha_2' => 'CY']);
        Country::create(['name' => 'Czech Republic', 'alpha_2' => 'CZ']);
        Country::create(['name' => 'Denmark', 'alpha_2' => 'DK']);
        Country::create(['name' => 'Djibouti', 'alpha_2' => 'DJ']);
        Country::create(['name' => 'Dominica', 'alpha_2' => 'DM']);
        Country::create(['name' => 'Dominican Republic', 'alpha_2' => 'DO']);
        Country::create(['name' => 'Ecuador', 'alpha_2' => 'EC']);
        Country::create(['name' => 'Egypt', 'alpha_2' => 'EG']);
        Country::create(['name' => 'El Salvador', 'alpha_2' => 'SV']);
        Country::create(['name' => 'Equatorial Guinea', 'alpha_2' => 'GQ']);
        Country::create(['name' => 'Eritrea', 'alpha_2' => 'ER']);
        Country::create(['name' => 'Estonia', 'alpha_2' => 'EE']);
        Country::create(['name' => 'Ethiopia', 'alpha_2' => 'ET']);
        Country::create(['name' => 'Falkland Islands', 'alpha_2' => 'FK']);
        Country::create(['name' => 'Faroe Islands', 'alpha_2' => 'FO']);
        Country::create(['name' => 'Fiji', 'alpha_2' => 'FJ']);
        Country::create(['name' => 'Finland', 'alpha_2' => 'FI']);
        Country::create(['name' => 'France', 'alpha_2' => 'FR']);
        Country::create(['name' => 'French Guiana', 'alpha_2' => 'GF']);
        Country::create(['name' => 'French Polynesia', 'alpha_2' => 'PF']);
        Country::create(['name' => 'French Southern Territories', 'alpha_2' => 'TF']);
        Country::create(['name' => 'Gabon', 'alpha_2' => 'GA']);
        Country::create(['name' => 'Gambia', 'alpha_2' => 'GM']);
        Country::create(['name' => 'Georgia', 'alpha_2' => 'GE']);
        Country::create(['name' => 'Germany', 'alpha_2' => 'DE']);
        Country::create(['name' => 'Ghana', 'alpha_2' => 'GH']);
        Country::create(['name' => 'Gibraltar', 'alpha_2' => 'GI']);
        Country::create(['name' => 'Greece', 'alpha_2' => 'GR']);
        Country::create(['name' => 'Greenland', 'alpha_2' => 'GL']);
        Country::create(['name' => 'Grenada', 'alpha_2' => 'GD']);
        Country::create(['name' => 'Guadeloupe', 'alpha_2' => 'GP']);
        Country::create(['name' => 'Guam', 'alpha_2' => 'GU']);
        Country::create(['name' => 'Guatemala', 'alpha_2' => 'GT']);
        Country::create(['name' => 'Guernsey', 'alpha_2' => 'GG']);
        Country::create(['name' => 'Guinea', 'alpha_2' => 'GN']);
        Country::create(['name' => 'Guinea-Bissau', 'alpha_2' => 'GW']);
        Country::create(['name' => 'Guyana', 'alpha_2' => 'GY']);
        Country::create(['name' => 'Haiti', 'alpha_2' => 'HT']);
        Country::create(['name' => 'Heard and Mcdonald Islands', 'alpha_2' => 'HM']);
        Country::create(['name' => 'Holy See', 'alpha_2' => 'VA']);
        Country::create(['name' => 'Honduras', 'alpha_2' => 'HN']);
        Country::create(['name' => 'Hungary', 'alpha_2' => 'HU']);
        Country::create(['name' => 'Iceland', 'alpha_2' => 'IS']);
        Country::create(['name' => 'India', 'alpha_2' => 'IN']);
        Country::create(['name' => 'Indonesia', 'alpha_2' => 'ID']);
        Country::create(['name' => 'Iran', 'alpha_2' => 'IR']);
        Country::create(['name' => 'Iraq', 'alpha_2' => 'IQ']);
        Country::create(['name' => 'Ireland', 'alpha_2' => 'IE']);
        Country::create(['name' => 'Isle of Man', 'alpha_2' => 'IM']);
        Country::create(['name' => 'Israel', 'alpha_2' => 'IL']);
        Country::create(['name' => 'Italy', 'alpha_2' => 'IT']);
        Country::create(['name' => 'Jamaica', 'alpha_2' => 'JM']);
        Country::create(['name' => 'Japan', 'alpha_2' => 'JP']);
        Country::create(['name' => 'Jersey', 'alpha_2' => 'JE']);
        Country::create(['name' => 'Jordan', 'alpha_2' => 'JO']);
        Country::create(['name' => 'Kazakhstan', 'alpha_2' => 'KZ']);
        Country::create(['name' => 'Kenya', 'alpha_2' => 'KE']);
        Country::create(['name' => 'Kiribati', 'alpha_2' => 'KI']);
        Country::create(['name' => 'North Korea', 'alpha_2' => 'KP']);
        Country::create(['name' => 'South Korea', 'alpha_2' => 'KR']);
        Country::create(['name' => 'Kuwait', 'alpha_2' => 'KW']);
        Country::create(['name' => 'Kyrgyzstan', 'alpha_2' => 'KG']);
        Country::create(['name' => 'Lao PDR', 'alpha_2' => 'LA']);
        Country::create(['name' => 'Latvia', 'alpha_2' => 'LV']);
        Country::create(['name' => 'Lebanon', 'alpha_2' => 'LB']);
        Country::create(['name' => 'Lesotho', 'alpha_2' => 'LS']);
        Country::create(['name' => 'Liberia', 'alpha_2' => 'LR']);
        Country::create(['name' => 'Libya', 'alpha_2' => 'LY']);
        Country::create(['name' => 'Liechtenstein', 'alpha_2' => 'LI']);
        Country::create(['name' => 'Lithuania', 'alpha_2' => 'LT']);
        Country::create(['name' => 'Luxembourg', 'alpha_2' => 'LU']);
        Country::create(['name' => 'Macedonia', 'alpha_2' => 'MK']);
        Country::create(['name' => 'Madagascar', 'alpha_2' => 'MG']);
        Country::create(['name' => 'Malawi', 'alpha_2' => 'MW']);
        Country::create(['name' => 'Malaysia', 'alpha_2' => 'MY']);
        Country::create(['name' => 'Maldives', 'alpha_2' => 'MV']);
        Country::create(['name' => 'Mali', 'alpha_2' => 'ML']);
        Country::create(['name' => 'Malta', 'alpha_2' => 'MT']);
        Country::create(['name' => 'Marshall Islands', 'alpha_2' => 'MH']);
        Country::create(['name' => 'Martinique', 'alpha_2' => 'MQ']);
        Country::create(['name' => 'Mauritania', 'alpha_2' => 'MR']);
        Country::create(['name' => 'Mauritius', 'alpha_2' => 'MU']);
        Country::create(['name' => 'Mayotte', 'alpha_2' => 'YT']);
        Country::create(['name' => 'Mexico', 'alpha_2' => 'MX']);
        Country::create(['name' => 'Micronesia', 'alpha_2' => 'FM']);
        Country::create(['name' => 'Moldova', 'alpha_2' => 'MD']);
        Country::create(['name' => 'Monaco', 'alpha_2' => 'MC']);
        Country::create(['name' => 'Mongolia', 'alpha_2' => 'MN']);
        Country::create(['name' => 'Montenegro', 'alpha_2' => 'ME']);
        Country::create(['name' => 'Montserrat', 'alpha_2' => 'MS']);
        Country::create(['name' => 'Morocco', 'alpha_2' => 'MA']);
        Country::create(['name' => 'Mozambique', 'alpha_2' => 'MZ']);
        Country::create(['name' => 'Myanmar', 'alpha_2' => 'MM']);
        Country::create(['name' => 'Namibia', 'alpha_2' => 'NA']);
        Country::create(['name' => 'Nauru', 'alpha_2' => 'NR']);
        Country::create(['name' => 'Nepal', 'alpha_2' => 'NP']);
        Country::create(['name' => 'Netherlands', 'alpha_2' => 'NL']);
        Country::create(['name' => 'Netherlands Antilles', 'alpha_2' => 'AN']);
        Country::create(['name' => 'New Caledonia', 'alpha_2' => 'NC']);
        Country::create(['name' => 'New Zealand', 'alpha_2' => 'NZ']);
        Country::create(['name' => 'Nicaragua', 'alpha_2' => 'NI']);
        Country::create(['name' => 'Niger', 'alpha_2' => 'NE']);
        Country::create(['name' => 'Nigeria', 'alpha_2' => 'NG']);
        Country::create(['name' => 'Niue', 'alpha_2' => 'NU']);
        Country::create(['name' => 'Norfolk Island', 'alpha_2' => 'NF']);
        Country::create(['name' => 'Northern Mariana Islands', 'alpha_2' => 'MP']);
        Country::create(['name' => 'Norway', 'alpha_2' => 'NO']);
        Country::create(['name' => 'Oman', 'alpha_2' => 'OM']);
        Country::create(['name' => 'Pakistan', 'alpha_2' => 'PK']);
        Country::create(['name' => 'Palau', 'alpha_2' => 'PW']);
        Country::create(['name' => 'Palestinian Territory', 'alpha_2' => 'PS']);
        Country::create(['name' => 'Panama', 'alpha_2' => 'PA']);
        Country::create(['name' => 'Papua New Guinea', 'alpha_2' => 'PG']);
        Country::create(['name' => 'Paraguay', 'alpha_2' => 'PY']);
        Country::create(['name' => 'Peru', 'alpha_2' => 'PE']);
        Country::create(['name' => 'Philippines', 'alpha_2' => 'PH']);
        Country::create(['name' => 'Pitcairn', 'alpha_2' => 'PN']);
        Country::create(['name' => 'Poland', 'alpha_2' => 'PL']);
        Country::create(['name' => 'Portugal', 'alpha_2' => 'PT']);
        Country::create(['name' => 'Puerto Rico', 'alpha_2' => 'PR']);
        Country::create(['name' => 'Qatar', 'alpha_2' => 'QA']);
        Country::create(['name' => 'Réunion', 'alpha_2' => 'RE']);
        Country::create(['name' => 'Romania', 'alpha_2' => 'RO']);
        Country::create(['name' => 'Russian Federation', 'alpha_2' => 'RU']);
        Country::create(['name' => 'Rwanda', 'alpha_2' => 'RW']);
        Country::create(['name' => 'Saint-Barthélemy', 'alpha_2' => 'BL']);
        Country::create(['name' => 'Saint Helena', 'alpha_2' => 'SH']);
        Country::create(['name' => 'Saint Kitts and Nevis', 'alpha_2' => 'KN']);
        Country::create(['name' => 'Saint Lucia', 'alpha_2' => 'LC']);
        Country::create(['name' => 'Saint-Martin (French part)', 'alpha_2' => 'MF']);
        Country::create(['name' => 'Saint Pierre and Miquelon', 'alpha_2' => 'PM']);
        Country::create(['name' => 'Saint Vincent and Grenadines', 'alpha_2' => 'VC']);
        Country::create(['name' => 'Samoa', 'alpha_2' => 'WS']);
        Country::create(['name' => 'San Marino', 'alpha_2' => 'SM']);
        Country::create(['name' => 'Sao Tome and Principe', 'alpha_2' => 'ST']);
        Country::create(['name' => 'Saudi Arabia', 'alpha_2' => 'SA']);
        Country::create(['name' => 'Senegal', 'alpha_2' => 'SN']);
        Country::create(['name' => 'Serbia', 'alpha_2' => 'RS']);
        Country::create(['name' => 'Seychelles', 'alpha_2' => 'SC']);
        Country::create(['name' => 'Sierra Leone', 'alpha_2' => 'SL']);
        Country::create(['name' => 'Singapore', 'alpha_2' => 'SG']);
        Country::create(['name' => 'Slovakia', 'alpha_2' => 'SK']);
        Country::create(['name' => 'Slovenia', 'alpha_2' => 'SI']);
        Country::create(['name' => 'Solomon Islands', 'alpha_2' => 'SB']);
        Country::create(['name' => 'Somalia', 'alpha_2' => 'SO']);
        Country::create(['name' => 'South Africa', 'alpha_2' => 'ZA']);
        Country::create(['name' => 'South Georgia and the South Sandwich Islands', 'alpha_2' => 'GS']);
        Country::create(['name' => 'South Sudan', 'alpha_2' => 'SS']);
        Country::create(['name' => 'Spain', 'alpha_2' => 'ES']);
        Country::create(['name' => 'Sri Lanka', 'alpha_2' => 'LK']);
        Country::create(['name' => 'Sudan', 'alpha_2' => 'SD']);
        Country::create(['name' => 'Suriname', 'alpha_2' => 'SR']);
        Country::create(['name' => 'Svalbard and Jan Mayen Islands', 'alpha_2' => 'SJ']);
        Country::create(['name' => 'Swaziland', 'alpha_2' => 'SZ']);
        Country::create(['name' => 'Sweden', 'alpha_2' => 'SE']);
        Country::create(['name' => 'Switzerland', 'alpha_2' => 'CH']);
        Country::create(['name' => 'Syrian Arab Republic', 'alpha_2' => 'SY']);
        Country::create(['name' => 'Taiwan', 'alpha_2' => 'TW']);
        Country::create(['name' => 'Tajikistan', 'alpha_2' => 'TJ']);
        Country::create(['name' => 'Tanzania', 'alpha_2' => 'TZ']);
        Country::create(['name' => 'Thailand', 'alpha_2' => 'TH']);
        Country::create(['name' => 'Timor-Leste', 'alpha_2' => 'TL']);
        Country::create(['name' => 'Togo', 'alpha_2' => 'TG']);
        Country::create(['name' => 'Tokelau', 'alpha_2' => 'TK']);
        Country::create(['name' => 'Tonga', 'alpha_2' => 'TO']);
        Country::create(['name' => 'Trinidad and Tobago', 'alpha_2' => 'TT']);
        Country::create(['name' => 'Tunisia', 'alpha_2' => 'TN']);
        Country::create(['name' => 'Turkey', 'alpha_2' => 'TR']);
        Country::create(['name' => 'Turkmenistan', 'alpha_2' => 'TM']);
        Country::create(['name' => 'Turks and Caicos Islands', 'alpha_2' => 'TC']);
        Country::create(['name' => 'Tuvalu', 'alpha_2' => 'TV']);
        Country::create(['name' => 'Uganda', 'alpha_2' => 'UG']);
        Country::create(['name' => 'Ukraine', 'alpha_2' => 'UA']);
        Country::create(['name' => 'United Arab Emirates', 'alpha_2' => 'AE']);
        Country::create(['name' => 'United Kingdom', 'alpha_2' => 'GB']);
        Country::create(['name' => 'United States of America', 'alpha_2' => 'US']);
        Country::create(['name' => 'US Minor Outlying Islands', 'alpha_2' => 'UM']);
        Country::create(['name' => 'Uruguay', 'alpha_2' => 'UY']);
        Country::create(['name' => 'Uzbekistan', 'alpha_2' => 'UZ']);
        Country::create(['name' => 'Vanuatu', 'alpha_2' => 'VU']);
        Country::create(['name' => 'Venezuela', 'alpha_2' => 'VE']);
        Country::create(['name' => 'Viet Nam', 'alpha_2' => 'VN']);
        Country::create(['name' => 'Virgin Islands, US', 'alpha_2' => 'VI']);
        Country::create(['name' => 'Wallis and Futuna Islands', 'alpha_2' => 'WF']);
        Country::create(['name' => 'Western Sahara', 'alpha_2' => 'EH']);
        Country::create(['name' => 'Yemen', 'alpha_2' => 'YE']);
        Country::create(['name' => 'Zambia', 'alpha_2' => 'ZM']);
        Country::create(['name' => 'Zimbabwe', 'alpha_2' => 'ZW']);
    }
}